kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: database
  namespace: devboard
spec:
  serviceName: database-svc                  # will review this
  replicas: 3
  selector:
    matchLabels:
      devboard: database
  template:
    metadata: 
      name: database-pod
      labels:
        devboard: database
    spec:
      containers:
        - name: database-container
          image: <image-name>                 #database image name
          ports: 
            - containerPort: <port-number>     #database port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                 name: secret
                 key: <key-name-1>
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                 name: secret
                 key: <key-name-2>    
          
   
