kind: Service
apiVersion: v1
metadata: 
  name: database
  namespace: devboard
spec:
  type: ClusterIP
  selector: 
    devboard: database
  ports:
    - protocol: TCP
      port: <port-number>           #Internal port services needed for ClusterIP
      targetPort: <port-number>     #Database Container port
