kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: devboard
spec: 
  replicas: 3
  selector: 
     matchLabels:
       devboard: frontend
  template:
     metadata:
       name: frontend-pod
       labels:
          devboard: frontend
       spec:
          containers: 
             - name: frontend-container
               image: <image-name>               #Image name from registry
               ports:
               - containerPort: <port-number>    #Container Port number to expose.
  
