kind: Secret
apiVersion: v1 
metadata:
  name: secret
  namespace: devboard
data:
  <key-name-1>: <value-name>  #Should be base64 encoded
  <key-name-2>: <value-name>  #Should be base64 encoded
  <key-name-2>: <value-name>  #Should be base64 encoded
